# https://blog.logto.io/zh-CN/automatic-github-workflow-rerun
name: Flutter Tag Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for accurate tag detection

      - name: Run flutter-build.yml
        id: flutter_build
        uses: ./.github/workflows/flutter-build.yml
        secrets: inherit
        with:
          upload-artifact: true
          upload-tag: ${{ github.ref_name }}

  retry:
    needs: run-flutter-tag-build
    runs-on: ubuntu-latest
    if: ${{ needs.run-flutter-tag-build.result == 'failure' && github.run_number <= 3 }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Output run number
        run: echo "RUN_NUMBER: $RUN_NUMBER"
      - name: Trigger Retry Workflow
        run: |
          gh workflow run "${{ github.workflow }}" --ref "${{ github.ref }}"
